# Form implementation generated from reading ui file 'pomodoro_timer.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import sys
import time

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import *
from PyQt6.QtGui import *
from PyQt6.QtWidgets import *



class PomodoroTimerGUI(QMainWindow):
    
    def __init__(self):
        super().__init__()
      

        self.timer = QTimer()
        self.DEFAULT_WORK_TIME = 1 # 25
        self.DEFAULT_SHORT_BREAK = 1# 5
        self.DEFAULT_LONG_BREAK = 1 # 15
        self.DEFAULT_NO_OF_CYCLES = 3
        self.current_cycle = 0
        self.short_breaks_taken = 0
        self.is_break_time = False
        self.current_timer_type = "Pomodoro"
     
        self.setupUi(self)


    def setupUi(self, pomodoroTimer):
        pomodoroTimer.setObjectName("pomodoroTimer")
        pomodoroTimer.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        pomodoroTimer.resize(620, 550)
        pomodoroTimer.setMinimumSize(QtCore.QSize(300, 300))
        pomodoroTimer.setMaximumSize(QtCore.QSize(620, 550))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(True)
        pomodoroTimer.setFont(font)
        icon_path = os.path.abspath("pomodoro-technique.png")
        icon = QIcon(icon_path)
        self.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=pomodoroTimer)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 621, 547))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.rb_pomodoro = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.rb_pomodoro.setObjectName("rb_pomodoro")
        self.horizontalLayout_2.addWidget(self.rb_pomodoro)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.rb_short_break = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.rb_short_break.setObjectName("rb_short_break")
        self.horizontalLayout_2.addWidget(self.rb_short_break)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.rb_long_break = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.rb_long_break.setObjectName("rb_long_break")
        self.horizontalLayout_2.addWidget(self.rb_long_break)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.lcd_min_timer = QtWidgets.QLCDNumber(parent=self.verticalLayoutWidget)
        self.lcd_min_timer.setMinimumSize(QtCore.QSize(75, 75))
        self.lcd_min_timer.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setItalic(True)
        self.lcd_min_timer.setFont(font)
        self.lcd_min_timer.setSmallDecimalPoint(False)
        self.lcd_min_timer.setDigitCount(2)
        self.lcd_min_timer.setProperty("intValue", 25)
        self.lcd_min_timer.setObjectName("lcd_min_timer")
        self.horizontalLayout_3.addWidget(self.lcd_min_timer)
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lcd_sec_timer = QtWidgets.QLCDNumber(parent=self.verticalLayoutWidget)
        self.lcd_sec_timer.setMinimumSize(QtCore.QSize(75, 75))
        self.lcd_sec_timer.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setItalic(True)
        self.lcd_sec_timer.setFont(font)
        self.lcd_sec_timer.setSmallDecimalPoint(False)
        self.lcd_sec_timer.setDigitCount(2)
        self.lcd_sec_timer.setObjectName("lcd_sec_timer")
        self.horizontalLayout_3.addWidget(self.lcd_sec_timer)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem10 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout.addItem(spacerItem10)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem12)
        self.btn_start = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setItalic(True)
        self.btn_start.setFont(font)
        self.btn_start.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btn_start.setIconSize(QtCore.QSize(20, 20))
        self.btn_start.setObjectName("btn_start")
        self.horizontalLayout_4.addWidget(self.btn_start)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem13)
        self.btn_stop = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setItalic(True)
        self.btn_stop.setFont(font)
        self.btn_stop.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btn_stop.setIconSize(QtCore.QSize(20, 20))
        self.btn_stop.setObjectName("btn_stop")
        self.horizontalLayout_4.addWidget(self.btn_stop)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem14)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem15)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem16 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout.addItem(spacerItem16)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem17)
        self.label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.lbl_current_cycle = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.lbl_current_cycle.setText("")
        self.lbl_current_cycle.setObjectName("lbl_current_cycle")
        self.horizontalLayout_5.addWidget(self.lbl_current_cycle)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem18)
        self.label_3 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.lbl_short_break = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.lbl_short_break.setText("")
        self.lbl_short_break.setObjectName("lbl_short_break")
        self.horizontalLayout_5.addWidget(self.lbl_short_break)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem19)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem20 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout.addItem(spacerItem20)
        pomodoroTimer.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=pomodoroTimer)
        self.statusbar.setObjectName("statusbar")
        pomodoroTimer.setStatusBar(self.statusbar)
        self.rb_pomodoro.setChecked(True)
        self.retranslateUi(pomodoroTimer)
        self.timer_seconds = self.DEFAULT_WORK_TIME * 60
        minutes = self.timer_seconds // 60 
        seconds = self.timer_seconds % 60
        self.lcd_sec_timer.display(f"{seconds:02d}")
        self.lcd_min_timer.display(f"{minutes:02d}")
        self.remaining_seconds = self.timer_seconds

        QtCore.QMetaObject.connectSlotsByName(pomodoroTimer)

    def retranslateUi(self, pomodoroTimer):
        _translate = QtCore.QCoreApplication.translate
        pomodoroTimer.setWindowTitle(_translate("pomodoroTimer", "Pomodoro Timer"))
        self.rb_pomodoro.setText(_translate("pomodoroTimer", "Pomodoro"))
        self.rb_short_break.setText(_translate("pomodoroTimer", "Short Break"))
        self.rb_long_break.setText(_translate("pomodoroTimer", "Long Break"))
        self.label.setText(_translate("pomodoroTimer", ":"))
        self.btn_start.setText(_translate("pomodoroTimer", "Start"))
        self.btn_stop.setText(_translate("pomodoroTimer", "Stop"))
        self.label_2.setText(_translate("pomodoroTimer", "Current Cycle :"))
        self.label_3.setText(_translate("pomodoroTimer", "Short Break :"))
        self.lbl_current_cycle.setText(f"{self.current_cycle} / {self.DEFAULT_NO_OF_CYCLES}")
        self.lbl_short_break.setText(f"{self.short_breaks_taken} / {self.DEFAULT_NO_OF_CYCLES - 1}")
        self.btn_start.clicked.connect(self.start_pomodoro)
        self.btn_stop.clicked.connect(self.stop_timer)
        self.rb_pomodoro.toggled.connect(self.select_timer)
        self.rb_short_break.toggled.connect(self.select_timer)
        self.rb_long_break.toggled.connect(self.select_timer)

    def select_timer(self):
        if self.rb_pomodoro.isChecked():
            self.timer_seconds = self.DEFAULT_WORK_TIME * 60
            self.remaining_seconds = self.timer_seconds
        elif self.rb_short_break.isChecked():
            self.timer_seconds = self.DEFAULT_SHORT_BREAK * 60
            self.remaining_seconds = self.timer_seconds
        elif self.rb_long_break.isChecked():
            self.timer_seconds = self.DEFAULT_LONG_BREAK * 60
            self.remaining_seconds = self.timer_seconds
        

        minutes = self.timer_seconds // 60 
        seconds = self.timer_seconds % 60
        print(f"Timer selected: {minutes} minutes, {seconds} seconds")
        self.lcd_sec_timer.display(f"{seconds:02d}")
        self.lcd_min_timer.display(f"{minutes:02d}")

    def show_dialog(self, title, message,icon):
        dlg = QMessageBox(self)
        dlg.setWindowTitle(title)
        dlg.setText(message)
        dlg.setStandardButtons(
            QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No
        )
        dlg.setIcon(icon)
        button = dlg.exec()

        if button == QMessageBox.StandardButton.Yes:
            print("Yes!")
        else:
            print("No!")

        return button

    def play_sound(self, title, message):
        try:
            os.system('afplay /System/Library/Sounds/Ping.aiff 2> /dev/null || echo -e "\a"')
            # os.system(f'notify-send "{title}" "{message}"')
        except Exception as e:
            print(e)
            print('\a')


    def update_timer(self):
        # This gets called automatically every second by QTimer
        if self.remaining_seconds > 0:
            self.remaining_seconds -= 1
            self.update_display()
        else:
            self.timer.stop()
            self.on_timer_completed()
            self.play_sound("Time Up", f"Pomodoro Timer completed")
    

    def on_timer_completed(self):
        print("Timer completed!")
        self.handle_ui_elements(disable=False)
        if self.is_break_time:
            self.play_sound("Break Time Up", "Break time completed!")
            self.ask_next_action_after_break()
        else:
            self.play_sound("Work Time Up", "Pomodoro work session completed!")
            self.current_cycle += 1
            self.ask_next_action_after_work()


    def handle_ui_elements(self, disable):
        self.rb_pomodoro.setDisabled(disable)
        self.rb_short_break.setDisabled(disable)
        self.rb_long_break.setDisabled(disable)
        self.btn_start.setDisabled(disable)
        self.btn_stop.setDisabled(not disable)
    
        self.lbl_current_cycle.setText(f"{self.current_cycle} / {self.DEFAULT_NO_OF_CYCLES}")
        self.lbl_short_break.setText(f"{self.short_breaks_taken} / {self.DEFAULT_NO_OF_CYCLES - 1}")
        # print(f"rb_pomodoro.isChecked(): {self.rb_pomodoro.isChecked()}, rb_short_break.isChecked(): {self.rb_short_break.isChecked()}, rb_long_break.isChecked(): {self.rb_long_break.isChecked()}")
        print(f"Current Timer Type : {self.current_timer_type}")
        if self.current_timer_type == "Pomodoro":
            if self.rb_pomodoro.isChecked() == False:
                self.rb_pomodoro.setChecked(True)
                self.rb_short_break.setChecked(False)
                self.rb_long_break.setChecked(False) 
        elif self.current_timer_type == "Short Break":
            if self.rb_short_break.isChecked() == False:
                self.rb_pomodoro.setChecked(False)
                self.rb_short_break.setChecked(True)
                self.rb_long_break.setChecked(False) 
        elif self.current_timer_type == "Long Break":
            if self.rb_long_break.isChecked() == False:
                self.rb_pomodoro.setChecked(False)
                self.rb_short_break.setChecked(False)
                self.rb_long_break.setChecked(True) 

        if disable:
            self.btn_start.setText("Running...")
        else:
            self.btn_start.setText("Start")
            self.select_timer()    


    def update_display(self):
        minutes = self.remaining_seconds // 60
        seconds = self.remaining_seconds % 60
    
        self.lcd_sec_timer.display(f"{seconds:02d}")
        self.lcd_min_timer.display(f"{minutes:02d}")
        print(f"Time : {minutes:02d}:{seconds:02d}", end="\r")


    def ask_next_action_after_work(self):
        print(f"Pomodoro timer cycle '{self.current_cycle}' of '{self.DEFAULT_NO_OF_CYCLES}' finished.")

        if self.current_cycle >= self.DEFAULT_NO_OF_CYCLES:
            message = f"Pomodoro timer cycle completed. \nYou can take a Long break of {self.DEFAULT_LONG_BREAK} minutes"
            button = self.show_dialog("Pomodoro Timer", message, QMessageBox.Icon.Information)
            
            if button == QMessageBox.StandardButton.Yes:
                self.current_timer_type = "Long Break"
                self.start_the_timer(self.DEFAULT_LONG_BREAK, is_break=True)
        else:
            message = f"Pomodoro timer cycle finished.\nYou can take a Short break '{self.short_breaks_taken+1}' for '{self.DEFAULT_SHORT_BREAK}' minutes. \nDo you want to start the short break now?"
            button = self.show_dialog("Pomodoro Timer", message, QMessageBox.Icon.Question)
            
            if button == QMessageBox.StandardButton.Yes:
                self.current_timer_type = "Short Break"
                self.short_breaks_taken += 1
                self.start_the_timer(self.DEFAULT_SHORT_BREAK, is_break=True)
            else:
                self.ask_start_next_cycle()

    def ask_next_action_after_break(self):
        message = "Break time completed!\nDo you want to start the next cycle of Pomodoro timer now?"
        button = self.show_dialog("Pomodoro Timer", message, QMessageBox.Icon.Question)
        
        if button == QMessageBox.StandardButton.Yes:
            self.current_timer_type = "Pomodoro"
            self.start_next_cycle()
        else:
            print("Pomodoro session paused.")

    def ask_start_next_cycle(self):
        message = "Do you want to start the next cycle of Pomodoro timer now?"
        button = self.show_dialog("Pomodoro Timer", message, QMessageBox.Icon.Question)
        
        if button == QMessageBox.StandardButton.Yes:
            self.current_cycle = 0
            self.short_breaks_taken = 0
            self.start_next_cycle()
        else:
            print("Pomodoro session paused.")

    def start_next_cycle(self):
        if self.current_cycle < self.DEFAULT_NO_OF_CYCLES:
            self.start_the_timer(self.DEFAULT_WORK_TIME, is_break=False)
        else:
            print("All Pomodoro cycles completed!")

    def start_the_timer(self, timer_minute, is_break=False):
        # Create and start QTimer
        self.is_break_time = is_break
        self.timer_seconds = timer_minute * 60
        self.remaining_seconds = self.timer_seconds

        if self.timer.isActive():
            self.timer.stop()
   
        self.timer.timeout.connect(self.update_timer)
        self.timer.start(1000)  # Update every second

        # Initial display
        self.handle_ui_elements(disable=True)
        self.update_display()



    def stop_timer(self):
            """Method to stop the timer manually"""
            if self.timer.isActive():
                button = self.show_dialog("Pomodoro Timer","Do you want to stop the timer ? (Y/N)",QMessageBox.Icon.Question)   
                if button == QMessageBox.StandardButton.Yes:    
                    self.timer.stop()
                    print("Timer stopped manually")
                    self.handle_ui_elements(disable=False)


    def start_pomodoro(self):
            print(f" -- Pomodoro timer started -- ")
            self.current_cycle = 0
            self.short_breaks_taken = 0
            self.is_break_time = False
            
            # Start the first work session
            self.start_the_timer(self.DEFAULT_WORK_TIME, is_break=False)

            
if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = PomodoroTimerGUI()
    ui.show()
    # MainWindow.show()
    app.exec()